const SUPABASE_URL = 'https://iaypuduwhvhomxlwzbjr.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlheXB1ZHV3aHZob214bHd6YmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNDk0MjgsImV4cCI6MjA5NDkyNTQyOH0.l8Hscptiglc-Alv-Yq3wB9Q3B4AQO_iG2zjNPyAQRwc';
